// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmNy-MvqkhQRDMhde_7WZMFN2B5rp8d_s',
    appId: '1:1051360580473:web:4834fa2caf330efe5f15a8',
    messagingSenderId: '1051360580473',
    projectId: 'note-2fc6c',
    authDomain: 'note-2fc6c.firebaseapp.com',
    databaseURL: 'https://note-2fc6c-default-rtdb.firebaseio.com',
    storageBucket: 'note-2fc6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRnO1AMci-fY48HizetchXm8H2NB18Gnw',
    appId: '1:1051360580473:android:6b34f70a1ca3a9dc5f15a8',
    messagingSenderId: '1051360580473',
    projectId: 'note-2fc6c',
    databaseURL: 'https://note-2fc6c-default-rtdb.firebaseio.com',
    storageBucket: 'note-2fc6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsvSYm5LYIDiCU3Ns8N2F4PPIgUiElKE',
    appId: '1:1051360580473:ios:831cfbd5b0fc4c975f15a8',
    messagingSenderId: '1051360580473',
    projectId: 'note-2fc6c',
    databaseURL: 'https://note-2fc6c-default-rtdb.firebaseio.com',
    storageBucket: 'note-2fc6c.firebasestorage.app',
    iosBundleId: 'com.example.contactRapide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXsvSYm5LYIDiCU3Ns8N2F4PPIgUiElKE',
    appId: '1:1051360580473:ios:831cfbd5b0fc4c975f15a8',
    messagingSenderId: '1051360580473',
    projectId: 'note-2fc6c',
    databaseURL: 'https://note-2fc6c-default-rtdb.firebaseio.com',
    storageBucket: 'note-2fc6c.firebasestorage.app',
    iosBundleId: 'com.example.contactRapide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmNy-MvqkhQRDMhde_7WZMFN2B5rp8d_s',
    appId: '1:1051360580473:web:88f97d12abe866955f15a8',
    messagingSenderId: '1051360580473',
    projectId: 'note-2fc6c',
    authDomain: 'note-2fc6c.firebaseapp.com',
    databaseURL: 'https://note-2fc6c-default-rtdb.firebaseio.com',
    storageBucket: 'note-2fc6c.firebasestorage.app',
  );
}
